export enum ObjectID {
  notSet = -1,
  viewPiantinaAngus,
  viewHome = viewPiantinaAngus,
  viewSezioneLavaggio,
  viewPrelavaggio,
  viewLavaggio,
  viewAsciugatura,
  viewPompaAcqua,
  viewContatoreAcqua,
  viewSensoreTemperatura,
  viewSensoreLivelloAcqua,
  viewPompa,
  viewVentilatore,
  viewSensoreUmidita,
  viewSezioneTrattamento,
  viewVascaPretrattamento,
  viewVascaPrimer,
  viewVascaFinisher,
  viewSensoreLivello,
  viewSensorePH,
  viewSezioneStoccaggio,
  viewImpilatore,
  viewMotore1,
  viewMotore2,
  btnLean	,
  btnDigital	,
  btnLeanChild1	,
  btnLeanChild2	,
  btnDigitalChild1	,
  btnDigitalChild2	,
  chart1	,
  chart2	,
  chart3	,
  chart4	,
  chart5	,
  chart6	,
  chart7	,
  chart8	,
  chart9	,
  chart10	,
  chart11	,
  chart12	,
  chart13
}
